/**
 * BINARIES Symposium Quiz - Master Seed Data
 * Contains exactly 20 Scientists and 20 Relational Questions (5 options each).
 */

const rawScientists = [
  {
    key: 'tesla',
    name: 'Nikola Tesla',
    image_url: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS71lhaKoUNGa1xA8uroIOq7TLZskX_QYaw4rY-ADJgRx5Vj-Wl2YCT_Iz0sSVYFZNMJLJzeeVklnfq1NsumsbtVySicjpKkk1oZOLa9BU&s=10',
    field: 'Electrical & Mechanical Engineering',
    country: 'Serbia / United States',
    lifespan: '1856 – 1943',
    description: 'Serbian-American engineer and physicist who designed the alternating-current (AC) electricity supply system. He patented the AC induction motor and pioneered high-voltage wireless power experiments.',
  },
  {
    key: 'volta',
    name: 'Alessandro Volta',
    image_url: 'https://cdn.britannica.com/49/147449-050-8B0F9C5F/Alessandro-Volta-two-inventions-electrophorus-battery.jpg?w=400&h=300&c=crop',
    field: 'Physics & Electrochemistry',
    country: 'Italy',
    lifespan: '1745 – 1827',
    description: 'Italian physicist, chemist, and pioneer of electricity who invented the voltaic pile in 1799, the first chemical electric battery. His breakthrough provided the first continuous source of electric current.',
  },
  {
    key: 'ohm',
    name: 'Georg Ohm',
    image_url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e6/Georg_Simon_Ohm_%281789-1854%29.jpg/960px-Georg_Simon_Ohm_%281789-1854%29.jpg',
    field: 'Physics & Mathematics',
    country: 'Germany',
    lifespan: '1789 – 1854',
    description: "German physicist and mathematician who formulated Ohm's law, defining the fundamental relationship between voltage, current, and resistance. His work laid the mathematical foundation for electrical circuit theory.",
  },
  {
    key: 'henry',
    name: 'Joseph Henry',
    image_url: 'https://encrypted-tbn0.gstatic.com/imagesq=tbn:ANd9GcRkQEHSefLtTERo1JLGt9Mggg4Mhg2Fx5XWjW3pkSWrTUg9r2UDXFml1uuCwtIakc7kVM8dwMB72CJgXN5k3-5l0z_zgiUFoq2ZMakoFw&s=10',
    field: 'Electromagnetism & Applied Physics',
    country: 'United States',
    lifespan: '1797 – 1878',
    description: 'American scientist who discovered electromagnetic self-inductance and invented the electrical relay. His innovations made long-distance telegraphy practical and formed the basis for modern electromagnetic switches.',
  },
  {
    key: 'edison',
    name: 'Thomas Alva Edison',
    image_url: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTqpHbVlmuYOE3X7VW_ilDDD1ylm5USJceo0ObOunOLMUc1bLBAOk55CqKHQvH9AYsqKuHyM6XK_W9IahACTfQ2JCXNon2oVNIXKBVgMJs&s=10',
    field: 'Applied Physics & Electrical Engineering',
    country: 'United States',
    lifespan: '1847 – 1931',
    description: 'Prolific American inventor who developed electric power distribution, the electrical safety fuse, the phonograph, and commercial incandescent lighting. He held over 1,093 patents shaping modern electrified cities.',
  },
  {
    key: 'faraday',
    name: 'Michael Faraday',
    image_url: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRM3r5zLXrwazaYAiovh2C7juswd1_xyaG1mBEgqzn0kJbSsckbxH1sPfxX1FzFINsbfBH2HlEr6EUdJsdfdMxrf-NXm4m-XiKsp5wDJQ&s=10',
    field: 'Electromagnetism & Electrochemistry',
    country: 'United Kingdom',
    lifespan: '1791 – 1867',
    description: 'English scientist who discovered electromagnetic induction, diamagnetism, and the laws of electrolysis. He constructed the first electric generator (dynamo) and established the principles of transformers.',
  },
  {
    key: 'shockley',
    name: 'William Shockley',
    image_url: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRSLa8P2dGBOP17VoZpHutwPkhba-mEK118DeGXDsFnMMvYaVeVg8gPFAp78qh5s3iUWbqqYTjR4Lw3bEaN6Jf5vNyBXApJKerO7POukQ&s=10',
    field: 'Solid-State Physics & Semiconductors',
    country: 'United States',
    lifespan: '1910 – 1989',
    description: 'American physicist and Nobel laureate who led the Bell Labs team that invented the point-contact and junction transistor. His pioneering work sparked the silicon semiconductor revolution.',
  },
  {
    key: 'kilby',
    name: 'Jack Kilby',
    image_url: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTaMdXBRncY_fZzcL-MaQSTf211ues0-sRQkLyh8rjHRgbwoEkxUbwv_4sHI-QUh0AE4QTU69b9yztcY3_sTuTeIF2meQsa26FEVZpx168&s=10',
    field: 'Electrical Engineering & Microelectronics',
    country: 'United States',
    lifespan: '1923 – 2005',
    description: 'American electrical engineer at Texas Instruments who created and demonstrated the first working integrated circuit in 1958. His breakthrough miniaturized complex electronic circuits onto a single semiconductor chip.',
  },
  {
    key: 'thomson',
    name: 'Elihu Thomson',
    image_url: 'https://upload.wikimedia.org/wikipedia/commons/1/1e/Elihu_thomson_ca1880.png',
    field: 'Electrical Engineering & Arc Lighting',
    country: 'United Kingdom / United States',
    lifespan: '1853 – 1937',
    description: 'English-born American electrical engineer whose patents on electrical generating equipment and arc lighting built General Electric. He contributed over 700 patents in power transmission and resistance welding.',
  },
  {
    key: 'joule',
    name: 'James Prescott Joule',
    image_url: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQLSbv0_ebi9bUGImFiUWifE6dpgBUZsQvgmDAXrTKhZ_sEQuuc7-tYQZInB4ZI5g3-c9Udaima-eOwm3xh8MvT0Ttrm05CCKc3U0zyf2I&s=10',
    field: 'Thermodynamics & Electrical Physics',
    country: 'United Kingdom',
    lifespan: '1818 – 1889',
    description: "English physicist who established the mechanical equivalent of heat and formulated Joule's first law of electrical heating. His work demonstrated the conservation of energy across thermal and electrical systems.",
  },
  {
    key: 'fleming',
    name: 'John Ambrose Fleming',
    image_url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/10/John_Ambrose_Fleming.jpg/800px-John_Ambrose_Fleming.jpg',
    field: 'Electrical Engineering & Thermionics',
    country: 'United Kingdom',
    lifespan: '1849 – 1945',
    description: "English electrical engineer and physicist who invented the thermionic valve (vacuum tube diode) in 1904. He also devised Fleming's left-hand and right-hand rules used universally in electromagnetism.",
  },
  {
    key: 'de_forest',
    name: 'Lee De Forest',
    image_url: 'https://upload.wikimedia.org/wikipedia/commons/4/4b/Lee_De_Forest.jpg',
    field: 'Electronics & Radio Technology',
    country: 'United States',
    lifespan: '1873 – 1961',
    description: 'American inventor who created the Audion vacuum tube triode by adding a control grid to the diode valve. This enabled electronic amplification, transforming radio communications, talking motion pictures, and early computers.',
  },
  {
    key: 'armstrong',
    name: 'Edwin Armstrong',
    image_url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d7/Edwin_Armstrong.jpg/800px-Edwin_Armstrong.jpg',
    field: 'Electrical Engineering & Telecommunications',
    country: 'United States',
    lifespan: '1890 – 1954',
    description: 'Pioneering electrical engineer who developed FM radio broadcasting, the regenerative circuit, and the superheterodyne receiver. His designs form the basis for virtually all modern radio, television, and wireless receivers.',
  },
  {
    key: 'franklin',
    name: 'Benjamin Franklin',
    image_url: 'https://upload.wikimedia.org/wikipedia/commons/c/cc/BenFranklinDuplessis.jpg',
    field: 'Natural Philosophy & Electricity',
    country: 'United States',
    lifespan: '1706 – 1790',
    description: 'American polymath who conducted seminal electrical experiments, characterized positive and negative charge, and proved lightning is electrical. He invented the lightning rod to protect structures from electrical strikes.',
  },
  {
    key: 'hertz',
    name: 'Heinrich Hertz',
    image_url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/25/Heinrich_Rudolf_Hertz.jpg/800px-Heinrich_Rudolf_Hertz.jpg',
    field: 'Electromagnetism & Experimental Physics',
    country: 'Germany',
    lifespan: '1857 – 1894',
    description: "German physicist who experimentally proved the existence of electromagnetic radio waves predicted by Maxwell's equations. He built the spark-gap transmitter and the first dipole antenna to detect wireless waves.",
  },
  {
    key: 'noyce',
    name: 'Robert Noyce',
    image_url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/42/Robert_Noyce_in_1959.jpg/800px-Robert_Noyce_in_1959.jpg',
    field: 'Semiconductor Physics & Microelectronics',
    country: 'United States',
    lifespan: '1927 – 1990',
    description: "Co-founder of Fairchild Semiconductor and Intel, nicknamed the 'Mayor of Silicon Valley'. He invented the silicon planar monolithic integrated circuit, which made mass-producing microchips commercially viable.",
  },
  {
    key: 'westinghouse',
    name: 'George Westinghouse',
    image_url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/69/George_Westinghouse.jpg/800px-George_Westinghouse.jpg',
    field: 'Mechanical & Electrical Engineering',
    country: 'United States',
    lifespan: '1846 – 1914',
    description: 'American entrepreneur and engineer who invented the railway air brake and championed alternating current power systems. His industrial vision established widespread electrification and fail-safe rail transportation.',
  },
  {
    key: 'holonyak',
    name: 'Nick Holonyak',
    image_url: 'https://upload.wikimedia.org/wikipedia/commons/a/a9/Nick_Holonyak_Jr._in_2004.jpg',
    field: 'Optoelectronics & Semiconductor Lasers',
    country: 'United States',
    lifespan: '1928 – 2022',
    description: 'American engineer and educator at General Electric who invented the first practical visible-spectrum (red) light-emitting diode in 1962. He also developed the first semiconductor visible laser.',
  },
  {
    key: 'babbage',
    name: 'Charles Babbage',
    image_url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6b/Charles_Babbage_-_1860.jpg/800px-Charles_Babbage_-_1860.jpg',
    field: 'Mechanical Computing & Mathematics',
    country: 'United Kingdom',
    lifespan: '1791 – 1871',
    description: "English mathematician, philosopher, and mechanical engineer renowned as the 'father of computing'. He conceived and designed the mechanical Analytical Engine, the direct precursor to modern programmable computers.",
  },
  {
    key: 'steinmetz',
    name: 'Charles Proteus Steinmetz',
    image_url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/21/Charles_Proteus_Steinmetz.jpg/800px-Charles_Proteus_Steinmetz.jpg',
    field: 'Electrical Engineering & Applied Mathematics',
    country: 'Germany / United States',
    lifespan: '1865 – 1923',
    description: 'German-born American mathematician and electrical engineer whose phasor representation and mathematical analysis of AC hysteresis made commercial alternating current power systems possible.',
  },
];

const rawQuestions = [
  // ROUND 1: 7 Questions (Easy / Medium)
  {
    scientistKey: 'tesla',
    question_text: "What is Nikola Tesla's notable invention?",
    option_a: 'Transformer',
    option_b: 'Induction motor',
    option_c: 'DC Motor',
    option_d: 'Synchronous Generator',
    option_e: 'Arc Lamp',
    correct_option: 'B',
    round: 'Round 1',
    round_number: 1,
    difficulty: 'easy',
    question_order: 0,
  },
  {
    scientistKey: 'volta',
    question_text: "What is Alessandro Volta's notable invention?",
    option_a: 'Battery',
    option_b: 'Capacitor',
    option_c: 'Resistor',
    option_d: 'Electromagnet',
    option_e: 'Telegraph',
    correct_option: 'A',
    round: 'Round 1',
    round_number: 1,
    difficulty: 'easy',
    question_order: 1,
  },
  {
    scientistKey: 'ohm',
    question_text: "What is Georg Ohm's fundamental discovery / law?",
    option_a: "Kirchhoff's Laws",
    option_b: "Faraday's Law",
    option_c: "Ohm's law",
    option_d: "Lenz's Law",
    option_e: "Maxwell's Equations",
    correct_option: 'C',
    round: 'Round 1',
    round_number: 1,
    difficulty: 'easy',
    question_order: 2,
  },
  {
    scientistKey: 'henry',
    question_text: "What is Joseph Henry's notable invention?",
    option_a: 'Telegraph',
    option_b: 'Battery',
    option_c: 'Transformer',
    option_d: 'Vacuum Tube',
    option_e: 'Relay',
    correct_option: 'E',
    round: 'Round 1',
    round_number: 1,
    difficulty: 'medium',
    question_order: 3,
  },
  {
    scientistKey: 'edison',
    question_text: "What is Thomas Alva Edison's notable safety invention for electrical circuits?",
    option_a: 'Circuit Breaker',
    option_b: 'Relay',
    option_c: 'Switch',
    option_d: 'Fuse',
    option_e: 'Isolator',
    correct_option: 'D',
    round: 'Round 1',
    round_number: 1,
    difficulty: 'easy',
    question_order: 4,
  },
  {
    scientistKey: 'faraday',
    question_text: "What is Michael Faraday's groundbreaking electromagnetic invention?",
    option_a: 'Electric Generator',
    option_b: 'Alternator',
    option_c: 'Transformer',
    option_d: 'Inductor',
    option_e: 'Cathode Ray Tube',
    correct_option: 'A',
    round: 'Round 1',
    round_number: 1,
    difficulty: 'easy',
    question_order: 5,
  },
  {
    scientistKey: 'shockley',
    question_text: "What is William Shockley's Nobel Prize-winning invention?",
    option_a: 'Diode',
    option_b: 'Integrated Circuit',
    option_c: 'Transistor',
    option_d: 'Microprocessor',
    option_e: 'Vacuum Tube',
    correct_option: 'C',
    round: 'Round 1',
    round_number: 1,
    difficulty: 'medium',
    question_order: 6,
  },

  // ROUND 2: 7 Questions (Easy / Medium)
  {
    scientistKey: 'kilby',
    question_text: "What is Jack Kilby's revolutionary electronic invention?",
    option_a: 'PCB',
    option_b: 'IC (Integrated Circuit)',
    option_c: 'Microcontroller',
    option_d: 'Transistor',
    option_e: 'Breadboard',
    correct_option: 'B',
    round: 'Round 2',
    round_number: 2,
    difficulty: 'medium',
    question_order: 0,
  },
  {
    scientistKey: 'thomson',
    question_text: "What is Elihu Thomson's major contribution to power systems?",
    option_a: 'AC Motor',
    option_b: 'Battery',
    option_c: 'Electric Meter',
    option_d: 'Electrical Generating Equipment',
    option_e: 'Transformer',
    correct_option: 'D',
    round: 'Round 2',
    round_number: 2,
    difficulty: 'medium',
    question_order: 1,
  },
  {
    scientistKey: 'joule',
    question_text: "What is James Prescott Joule's fundamental electrical discovery?",
    option_a: 'Electrical Cooling',
    option_b: 'Electromagnetism',
    option_c: 'Electroplating',
    option_d: 'Thermocouple',
    option_e: 'Electrical Heating',
    correct_option: 'E',
    round: 'Round 2',
    round_number: 2,
    difficulty: 'easy',
    question_order: 2,
  },
  {
    scientistKey: 'fleming',
    question_text: "What is John Ambrose Fleming's foundational electronics invention?",
    option_a: 'Triode',
    option_b: 'Vacuum Tube (Thermionic Valve)',
    option_c: 'Transistor',
    option_d: 'Capacitor',
    option_e: 'Inductor',
    correct_option: 'B',
    round: 'Round 2',
    round_number: 2,
    difficulty: 'medium',
    question_order: 3,
  },
  {
    scientistKey: 'de_forest',
    question_text: "What is Lee De Forest's landmark amplifying invention?",
    option_a: 'Triode (Audion)',
    option_b: 'Magnetron',
    option_c: 'Klystron',
    option_d: 'Pentode',
    option_e: 'Cathode Ray Tube',
    correct_option: 'A',
    round: 'Round 2',
    round_number: 2,
    difficulty: 'medium',
    question_order: 4,
  },
  {
    scientistKey: 'armstrong',
    question_text: "What is Edwin Armstrong's high-fidelity broadcasting invention?",
    option_a: 'AM Radio',
    option_b: 'Television',
    option_c: 'FM Radio',
    option_d: 'Radar',
    option_e: 'Telegraph',
    correct_option: 'C',
    round: 'Round 2',
    round_number: 2,
    difficulty: 'medium',
    question_order: 5,
  },
  {
    scientistKey: 'franklin',
    question_text: "What is Benjamin Franklin's iconic electrical safety invention?",
    option_a: 'Battery',
    option_b: 'Leyden Jar',
    option_c: 'Electrometer',
    option_d: 'Lightning Rod',
    option_e: 'Kite Antenna',
    correct_option: 'D',
    round: 'Round 2',
    round_number: 2,
    difficulty: 'easy',
    question_order: 6,
  },

  // ROUND 3: 6 Questions (Medium / Hard)
  {
    scientistKey: 'hertz',
    question_text: "What is Heinrich Hertz's pioneering RF antenna invention?",
    option_a: 'Parabolic Antenna',
    option_b: 'Yagi-Uda Antenna',
    option_c: 'Loop Antenna',
    option_d: 'Monopole Antenna',
    option_e: 'Dipole Antenna',
    correct_option: 'E',
    round: 'Round 3',
    round_number: 3,
    difficulty: 'medium',
    question_order: 0,
  },
  {
    scientistKey: 'noyce',
    question_text: "What is Robert Noyce's silicon breakthrough invention?",
    option_a: 'Monolithic IC (Silicon)',
    option_b: 'Germanium IC',
    option_c: 'Microprocessor',
    option_d: 'CMOS',
    option_e: 'FinFET',
    correct_option: 'A',
    round: 'Round 3',
    round_number: 3,
    difficulty: 'hard',
    question_order: 1,
  },
  {
    scientistKey: 'westinghouse',
    question_text: "What is George Westinghouse's life-saving transport invention?",
    option_a: 'AC Transformer',
    option_b: 'Railway Air Brake',
    option_c: 'Dynamo',
    option_d: 'Electric Locomotive',
    option_e: 'Steam Engine',
    correct_option: 'B',
    round: 'Round 3',
    round_number: 3,
    difficulty: 'medium',
    question_order: 2,
  },
  {
    scientistKey: 'holonyak',
    question_text: "What is Nick Holonyak's revolutionary optical invention?",
    option_a: 'Blue LED',
    option_b: 'OLED',
    option_c: 'Visible Red LED',
    option_d: 'LCD',
    option_e: 'Plasma Display',
    correct_option: 'C',
    round: 'Round 3',
    round_number: 3,
    difficulty: 'hard',
    question_order: 3,
  },
  {
    scientistKey: 'babbage',
    question_text: "What is Charles Babbage's visionary mechanical computing invention?",
    option_a: 'ENIAC',
    option_b: 'Turing Machine',
    option_c: 'Pascaline',
    option_d: 'Analytical Engine',
    option_e: 'Abacus',
    correct_option: 'D',
    round: 'Round 3',
    round_number: 3,
    difficulty: 'easy',
    question_order: 4,
  },
  {
    scientistKey: 'steinmetz',
    question_text: "What is Charles Proteus Steinmetz's essential AC engineering development?",
    option_a: 'Phasor representation of AC',
    option_b: 'DC Motor Commutation',
    option_c: 'Skin Effect',
    option_d: 'Dielectric Breakdown',
    option_e: 'Eddy Currents',
    correct_option: 'A',
    round: 'Round 3',
    round_number: 3,
    difficulty: 'hard',
    question_order: 5,
  },
];

const components = [
  {
    id: 'comp_555_timer',
    name: 'NE555 Precision Timer IC',
    image_url: 'https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=400&q=80',
    description: 'Iconic 8-pin integrated circuit designed by Hans Camenzind in 1971 for precision timing pulses, delays, and oscillators.',
    category: 'Integrated Circuit',
    active: true,
  },
  {
    id: 'comp_microcontroller',
    name: 'ATmega328P Microcontroller',
    image_url: 'https://images.unsplash.com/photo-1550751827-4bd374c3f58b?auto=format&fit=crop&w=400&q=80',
    description: 'High performance 8-bit AVR RISC microcontroller powering embedded symposium robotics and IoT systems.',
    category: 'Processor',
    active: true,
  },
  {
    id: 'comp_photodiode',
    name: 'Silicon PIN Photodiode',
    image_url: 'https://images.unsplash.com/photo-1597733336794-12d05021d510?auto=format&fit=crop&w=400&q=80',
    description: 'High-speed semiconductor light sensor converting photon flux directly into electrical current for fiber optics and sensors.',
    category: 'Optoelectronics',
    active: true,
  },
  {
    id: 'comp_logic_gate',
    name: '74HC08 Quad 2-Input AND Gate',
    image_url: 'https://images.unsplash.com/photo-1517420704952-d9f39e95b43e?auto=format&fit=crop&w=400&q=80',
    description: 'Standard high-speed CMOS digital logic IC executing fundamental Boolean conjunction operations.',
    category: 'Digital Logic',
    active: true,
  },
];

const winners = [
  {
    id: 'win_1',
    position: 1,
    team_name: 'Quantum Pioneers',
    participant_name: 'Dr. Evelyn Reed & Marcus Vance',
    score: 980,
    completion_time: '02:15',
  },
  {
    id: 'win_2',
    position: 2,
    team_name: 'Neural Net Hackers',
    participant_name: 'Sophia Chen & Alex Rivera',
    score: 890,
    completion_time: '02:48',
  },
  {
    id: 'win_3',
    position: 3,
    team_name: 'Binary Titans',
    participant_name: 'Aarav Patel & Priya Sharma',
    score: 810,
    completion_time: '03:12',
  },
  {
    id: 'win_4',
    position: 4,
    team_name: 'Silicon Sparks',
    participant_name: 'Liam Zhang & Chloe Dubois',
    score: 740,
    completion_time: '03:40',
  },
];

module.exports = {
  rawScientists,
  rawQuestions,
  components,
  winners,
};
